config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def create
    Product.create!(name: product_params[:name], version: product_params[:version])
    flash[:notice] = 'Product created successfully'
    redirect_to products_path
  end

  private
  def product_params
    params.permit(:name, :version)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='flash'><%=flash[:notice]%></div>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>Products Listing</h1>
<table>
<tr>
  <td>Name</td>
  <td>Version</td>
</tr>
<% @products.each do |product| %>
<tr>
  <td><%= product.name -%></td>
  <td><%= product.version -%></td>
</tr>
<% end %>
</table>
<br>
<div class="product">
  <a href= "<%=new_product_path-%>">Create Product</a>
</div>

app/views/products/new.html.erb
<h1>Enter Product Details</h1>
<div class="product">
  <%= form_tag(products_path) do -%>
    Name: <%= text_field_tag 'name' -%>
    Version: <%= text_field_tag 'version' -%>
    <%= submit_tag 'Save' -%>
  <% end %>
</div>